"""initialize

Revision ID: 90199cdf1e57
Revises: 
Create Date: 2026-01-20 20:22:51.813431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90199cdf1e57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_team_index',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('current_iteration', sa.Boolean(), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('nickname', sa.String(length=256), nullable=False),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('year_active_til', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'nickname', 'year_active_til')
    )
    op.create_table('modern_team_index',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('abrev', sa.String(length=3), nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', 'abrev')
    )
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.BigInteger(), nullable=True),
    sa.Column('home_team_abrev', sa.String(length=3), nullable=True),
    sa.Column('away_team_id', sa.BigInteger(), nullable=True),
    sa.Column('away_team_abrev', sa.String(length=3), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('season_type', sa.Text(), nullable=True),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id', 'away_team_abrev'], ['modern_team_index.id', 'modern_team_index.abrev'], ),
    sa.ForeignKeyConstraint(['home_team_id', 'home_team_abrev'], ['modern_team_index.id', 'modern_team_index.abrev'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_team_performance',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('team_abrev', sa.String(length=3), nullable=True),
    sa.Column('mins', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('overtime', sa.Boolean(), nullable=True),
    sa.Column('field_goals_made', sa.Integer(), nullable=True),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=True),
    sa.Column('field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('three_pointers_made', sa.Integer(), nullable=True),
    sa.Column('three_pointers_attempted', sa.Integer(), nullable=True),
    sa.Column('three_pointer_percentage', sa.Float(), nullable=True),
    sa.Column('free_throws_made', sa.Integer(), nullable=True),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=True),
    sa.Column('free_throw_percentage', sa.Float(), nullable=True),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('total_rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('personal_fouls', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['team_id', 'team_abrev'], ['modern_team_index.id', 'modern_team_index.abrev'], ),
    sa.PrimaryKeyConstraint('game_id', 'team_id')
    )
    op.create_table('pbp_raw_event',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.Text(), nullable=True),
    sa.Column('event_num', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_subtype', sa.Text(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('clock', postgresql.INTERVAL(), nullable=True),
    sa.Column('home_team_id', sa.BigInteger(), nullable=True),
    sa.Column('away_team_id', sa.BigInteger(), nullable=True),
    sa.Column('home_team_abrev', sa.String(length=3), nullable=True),
    sa.Column('away_team_abrev', sa.String(length=3), nullable=True),
    sa.Column('possession_team_id', sa.BigInteger(), nullable=True),
    sa.Column('possession_team_abrev', sa.String(length=3), nullable=True),
    sa.Column('event_team_id', sa.BigInteger(), nullable=True),
    sa.Column('event_team_abrev', sa.String(length=3), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=True),
    sa.Column('shooter_id', sa.BigInteger(), nullable=True),
    sa.Column('assister_id', sa.BigInteger(), nullable=True),
    sa.Column('jump_ball_winner_id', sa.BigInteger(), nullable=True),
    sa.Column('jump_ball_loser_id', sa.BigInteger(), nullable=True),
    sa.Column('jump_ball_recovered_id', sa.BigInteger(), nullable=True),
    sa.Column('rebounder_id', sa.BigInteger(), nullable=True),
    sa.Column('turnover_id', sa.BigInteger(), nullable=True),
    sa.Column('foul_drawn_id', sa.BigInteger(), nullable=True),
    sa.Column('fouler_id', sa.BigInteger(), nullable=True),
    sa.Column('stealer_id', sa.BigInteger(), nullable=True),
    sa.Column('blocker_id', sa.BigInteger(), nullable=True),
    sa.Column('sub_in_id', sa.BigInteger(), nullable=True),
    sa.Column('sub_out_id', sa.BigInteger(), nullable=True),
    sa.Column('foul_is_technical', sa.Boolean(), nullable=True),
    sa.Column('foul_is_personal', sa.Boolean(), nullable=True),
    sa.Column('foul_is_offensive', sa.Boolean(), nullable=True),
    sa.Column('team_turnover', sa.Boolean(), nullable=True),
    sa.Column('team_rebound', sa.Boolean(), nullable=True),
    sa.Column('offensive_rebound', sa.Boolean(), nullable=True),
    sa.Column('side', sa.Text(), nullable=True),
    sa.Column('descriptor', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('area_detail', sa.Text(), nullable=True),
    sa.Column('shot_distance', sa.Float(), nullable=True),
    sa.Column('shot_made', sa.Boolean(), nullable=True),
    sa.Column('shot_value', sa.Integer(), nullable=True),
    sa.Column('shot_x', sa.Float(), nullable=True),
    sa.Column('shot_y', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assister_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['away_team_id', 'away_team_abrev'], ['modern_team_index.id', 'modern_team_index.abrev'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['event_team_id', 'event_team_abrev'], ['modern_team_index.id', 'modern_team_index.abrev'], ),
    sa.ForeignKeyConstraint(['foul_drawn_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['fouler_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['home_team_id', 'home_team_abrev'], ['modern_team_index.id', 'modern_team_index.abrev'], ),
    sa.ForeignKeyConstraint(['jump_ball_loser_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['jump_ball_recovered_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['jump_ball_winner_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['possession_team_id', 'possession_team_abrev'], ['modern_team_index.id', 'modern_team_index.abrev'], ),
    sa.ForeignKeyConstraint(['rebounder_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['shooter_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['stealer_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['sub_in_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['sub_out_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['turnover_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'event_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pbp_raw_event')
    op.drop_table('game_team_performance')
    op.drop_table('game')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('player')
    op.drop_table('modern_team_index')
    op.drop_table('historical_team_index')
    # ### end Alembic commands ###
